name: animationmusic
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2
  get_it: ^5.0.6
  http: ^0.12.2
  flushbar: ^1.10.4
  youtube_player_flutter: ^7.0.0+7
  cupertino_icons: ^1.0.0
  animated_text_kit: ^3.1.0
  integration_test: ^1.0.2
  flutter_inappwebview: ^4.0.0+4
  video_player: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  mobx_codegen: ^1.1.2
  build_runner: ^1.11.1

flutter:
  uses-material-design: true
